import { StyleSheet, Platform } from "react-native";
import { Colors, Spacing, Radius, Layout } from "../theme";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.background },
  modalScreen: { flex: 1, backgroundColor: Colors.background },
  homePadding: { flex: 1, paddingHorizontal: Spacing.xxl },

  homeHeaderInline: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    marginBottom: 40,
  },

  greeting: { fontSize: 16, color: Colors.textMuted, fontWeight: "500" },
  userName: { fontSize: 36, fontWeight: "800", color: Colors.text },
  mainActionBtn: {
    backgroundColor: Colors.text,
    paddingVertical: 18,
    borderRadius: 18,
    alignItems: "center",
    marginBottom: 20,
  },
  mainActionText: { color: Colors.background, fontSize: 18, fontWeight: "700" },
  headerContainer: {
    backgroundColor: Colors.background,
    borderBottomWidth: 1,
    borderBottomColor: Colors.card,
  },
  headerContentFlex: {
    height: 44,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
  },
  headerTitleContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  headerRightActionGroup: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    width: 80,
  },
  headerTitleStatic: {
    color: Colors.text,
    fontSize: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  headerTitleInput: {
    color: Colors.text,
    fontSize: 18,
    fontWeight: "700",
    flex: 1,
    width: "100%",
  },
  headerSideBtn: {
    width: 80,
    height: 44,
    justifyContent: "center",
    alignItems: "flex-start",
    paddingLeft: 4,
  },
  customBackChevron: {
    width: 13,
    height: 13,
    borderLeftWidth: 3,
    borderBottomWidth: 3,
    borderColor: Colors.text,
    transform: [{ rotate: "45deg" }],
  },
  settingsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 30,
    backgroundColor: Colors.card,
    padding: 20,
    borderRadius: Radius.lg,
  },
  toggleGroup: {
    flexDirection: "row",
    backgroundColor: Colors.border,
    borderRadius: 10,
    padding: 4,
  },
  toggleBtn: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  toggleBtnActive: { backgroundColor: Colors.borderStrong },
  toggleBtnActiveOn: { backgroundColor: Colors.accent },
  toggleBtnActiveOff: { backgroundColor: Colors.dangerAlt },
  toggleText: { color: Colors.textMuted, fontWeight: "700" },
  toggleTextActive: { color: Colors.text },
  searchBarContainer: {
    paddingHorizontal: Layout.screenPadding,
    paddingVertical: 10,
    backgroundColor: Colors.background,
  },
  searchBarInput: {
    backgroundColor: Colors.card,
    height: 44,
    borderRadius: Radius.md,
    paddingHorizontal: 15,
    color: Colors.text,
    fontSize: 16,
  },
  filterContainer: {
    paddingVertical: 12,
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.border,
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: Radius.xl,
    backgroundColor: Colors.card,
    marginRight: 8,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  filterChipActive: { backgroundColor: Colors.text, borderColor: Colors.text },
  filterChipText: { color: Colors.textMuted, fontWeight: "700", fontSize: 14 },
  filterChipTextActive: { color: Colors.background },
  sectionHeader: {
    backgroundColor: Colors.background,
    paddingTop: 12,
    paddingBottom: 16,
    paddingHorizontal: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionHeaderText: {
    color: Colors.textMuted,
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  sectionCountText: {
    color: Colors.textSubtle,
    fontSize: 12,
    fontWeight: "600",
  },
  searchItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: Layout.screenPadding,
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.card,
  },
  searchItemText: { color: Colors.text, fontSize: 17, fontWeight: "600" },
  searchItemSubtext: { color: Colors.textMuted, fontSize: 12, marginTop: 2 },
  plusIconCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(50, 215, 75, 0.1)",
    justifyContent: "center",
    alignItems: "center",
  },
  searchItemPlus: {
    color: Colors.accent,
    fontSize: 20,
    fontWeight: "600",
    marginTop: -2,
  },
  createExerciseTrigger: {
    padding: 16,
    alignItems: "center",
    backgroundColor: Colors.background,
  },
  createExerciseTriggerText: {
    color: Colors.accent,
    fontSize: 16,
    fontWeight: "700",
    textAlign: "center",
  },
  timerBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: Colors.cardAlt,
    padding: 16,
    borderRadius: Radius.xl,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "rgba(50, 215, 75, 0.35)",
    ...Platform.select({ android: { elevation: 4 } }),
  },
  timerInfo: { flexDirection: "column" },
  timerLabel: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },
  timerTime: { color: Colors.accent, fontSize: 24, fontWeight: "800" },
  timerActions: { flexDirection: "row" },
  timerBtn: {
    backgroundColor: Colors.accent,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: Radius.pill,
    marginLeft: 8,
    minWidth: 62,
    alignItems: "center",
  },
  timerBtnText: { color: Colors.text, fontWeight: "800", fontSize: 14 },
  vitalStatCard: {
    backgroundColor: Colors.card,
    padding: 24,
    borderRadius: 24,
    marginBottom: 16,
  },
  statLabel: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
    marginBottom: 8,
  },
  statValue: { color: Colors.text, fontSize: 36, fontWeight: "900" },
  statUnit: { color: Colors.textSubtle, fontSize: 22, fontWeight: "600" },
  mainChartCard: {
    backgroundColor: Colors.card,
    padding: 24,
    borderRadius: 24,
    minHeight: 280,
  },
  chartWrapper: {
    marginTop: 24,
    height: 180,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-around",
  },
  barContainer: { alignItems: "center", width: 40 },
  barValueLabel: {
    color: Colors.text,
    fontSize: 10,
    fontWeight: "800",
    marginBottom: 6,
  },
  barShape: { width: 18, borderRadius: 4 },
  barDateLabel: {
    color: Colors.textSubtle,
    fontSize: 10,
    fontWeight: "700",
    marginTop: 12,
  },
  chartEmptyState: { flex: 1, justifyContent: "center", alignItems: "center" },
  summaryCard: {
    backgroundColor: Colors.card,
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
  },
  summaryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    alignItems: "center",
  },
  summaryLabel: {
    fontSize: 13,
    color: Colors.textMuted,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  summaryChevron: { color: Colors.textSubtle, fontSize: 24 },
  summaryTitle: { fontSize: 22, color: Colors.text, fontWeight: "700" },
  summaryMeta: { fontSize: 15, color: Colors.textMuted, marginTop: 6 },
  prBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: Radius.md,
  },
  prBadgeText: { color: Colors.background, fontSize: 10, fontWeight: "800" },
  workoutOverviewCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.xxl,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Platform.select({
      android: { elevation: 2 },
      ios: {
        shadowColor: "#000",
        shadowOpacity: 0.18,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 6 },
      },
    }),
  },
  workoutOverviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  workoutOverviewKicker: {
    color: Colors.accent,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 2,
    marginBottom: 5,
  },
  workoutOverviewTitle: {
    color: Colors.text,
    fontSize: 22,
    fontWeight: "900",
  },
  workoutOverviewActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  workoutOverviewAction: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: Radius.pill,
    backgroundColor: "rgba(50, 215, 75, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(50, 215, 75, 0.28)",
  },
  workoutOverviewActionText: {
    color: Colors.accent,
    fontSize: 13,
    fontWeight: "900",
    marginLeft: 5,
  },
  workoutOverviewStatsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: "hidden",
  },
  workoutOverviewStat: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  workoutOverviewStatValue: {
    color: Colors.text,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 4,
  },
  workoutOverviewStatLabel: {
    color: Colors.textMuted,
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  workoutOverviewDivider: {
    width: 1,
    backgroundColor: Colors.border,
    marginVertical: 12,
  },
  reorderNotice: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(50, 215, 75, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(50, 215, 75, 0.22)",
    borderRadius: Radius.lg,
    padding: 14,
    marginBottom: 16,
  },
  reorderNoticeText: {
    flex: 1,
    color: Colors.text,
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
    marginLeft: 10,
  },
  exerciseCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.xxl,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Platform.select({
      android: { elevation: 1 },
      ios: {
        shadowColor: "#000",
        shadowOpacity: 0.12,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 4 },
      },
    }),
  },
  exerciseTitle: { fontSize: 21, fontWeight: "900", color: Colors.text },
  moveBtn: {
    backgroundColor: Colors.border,
    width: 32,
    height: 32,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 6,
  },
  moveBtnText: { color: Colors.text, fontSize: 14 },
  exerciseOptionsBtn: { paddingLeft: 10, paddingRight: 4, paddingVertical: 4 },
  exerciseOptionsIcon: { color: Colors.text, fontSize: 22, fontWeight: "600" },
  exerciseDragHandle: {
    width: 34,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 1,
    marginRight: 8,
  },

  exerciseDragCompactCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.xl,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    ...Platform.select({
      android: { elevation: 2 },
      ios: {
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 7,
        shadowOffset: { width: 0, height: 3 },
      },
    }),
  },
  exerciseDragCompactCardActive: {
    borderColor: Colors.accent,
    backgroundColor: Colors.cardAlt,
    ...Platform.select({
      android: { elevation: 9 },
      ios: {
        shadowColor: Colors.accent,
        shadowOpacity: 0.18,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 8 },
      },
    }),
  },
  exerciseDragCompactContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  exerciseDragCompactTitle: {
    color: Colors.text,
    fontSize: 18,
    fontWeight: "900",
  },
  exerciseDragCompactMeta: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: "800",
    marginTop: 2,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  exerciseCardDragging: {
    borderColor: Colors.accent,
    backgroundColor: Colors.cardAlt,
    ...Platform.select({
      android: { elevation: 8 },
      ios: {
        shadowColor: Colors.accent,
        shadowOpacity: 0.18,
        shadowRadius: 14,
        shadowOffset: { width: 0, height: 8 },
      },
    }),
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    columnGap: 8,
  },
  setInput: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    color: Colors.text,
    fontSize: 16,
    fontWeight: "800",
    textAlign: "center",
    paddingVertical: Platform.OS === "android" ? 9 : 11,
    minHeight: 44,
    borderWidth: 1,
    borderColor: Colors.border,
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  checkOff: {
    backgroundColor: Colors.surface,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.border,
    // No marginHorizontal — controlled by row gap.
    justifyContent: "center",
    alignItems: "center",
  },
  checkOn: {
    backgroundColor: Colors.accent,
    height: 44,
    borderRadius: 14,
    // No marginHorizontal — controlled by row gap.
    justifyContent: "center",
    alignItems: "center",
  },
  checkIcon: { color: Colors.text, fontSize: 18, fontWeight: "900" },
  scrollContent: { padding: Layout.screenPadding, paddingBottom: 220 },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0,0,0,0.92)",
    paddingHorizontal: Layout.screenPadding,
    paddingTop: 14,
    paddingBottom: 40,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  finishButton: {
    backgroundColor: Colors.accent,
    paddingVertical: 17,
    borderRadius: Radius.xl,
    alignItems: "center",
    ...Platform.select({ android: { elevation: 3 } }),
  },
  finishButtonText: { color: Colors.text, fontSize: 18, fontWeight: "800" },
  swipeContainer: {
    marginTop: 0,
    marginBottom: 16,
    overflow: "hidden",
    borderRadius: 24,
  },
  swipeableCard: { backgroundColor: Colors.card },
  addExerciseCard: {
    borderStyle: "dashed",
    borderWidth: 1.5,
    borderColor: "rgba(50, 215, 75, 0.4)",
    backgroundColor: "rgba(50, 215, 75, 0.06)",
    borderRadius: Radius.xxl,
    padding: 22,
    alignItems: "center",
    marginTop: 4,
  },
  addExerciseIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(50, 215, 75, 0.14)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  addExerciseText: { color: Colors.text, fontSize: 17, fontWeight: "900" },
  addExerciseSubtext: {
    color: Colors.textMuted,
    fontSize: 13,
    fontWeight: "700",
    marginTop: 4,
    textAlign: "center",
  },
  addSetRow: {
    marginTop: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
    borderRadius: Radius.lg,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  addSetText: { color: Colors.accent, fontSize: 15, fontWeight: "900" },
  setNumber: {
    color: Colors.textMuted,
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  actionMenuContent: {
    backgroundColor: Colors.card,
    padding: 20,
    borderRadius: 24,
    width: "90%",
    alignItems: "center",
  },
  actionMenuTitle: {
    color: Colors.textMuted,
    fontSize: 13,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 20,
  },
  actionMenuBtn: {
    width: "100%",
    backgroundColor: Colors.border,
    borderRadius: Radius.md,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 10,
  },
  actionMenuBtnDestructive: { backgroundColor: Colors.dangerAlt },
  actionMenuBtnCancel: {
    width: "100%",
    backgroundColor: Colors.background,
    borderRadius: Radius.md,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  actionMenuBtnText: { color: Colors.text, fontSize: 17, fontWeight: "700" },
  actionMenuBtnTextCancel: { color: Colors.text, fontWeight: "600" },
  actionMenuSubtitle: {
    color: Colors.textMuted,
    fontSize: 14,
    fontWeight: "700",
    marginTop: -12,
    marginBottom: 18,
    maxWidth: "100%",
  },
  actionSheetRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  actionSheetRowDanger: {
    backgroundColor: "rgba(255, 59, 48, 0.08)",
    borderColor: "rgba(255, 59, 48, 0.22)",
  },
  actionSheetIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(50, 215, 75, 0.12)",
    marginRight: 12,
  },
  actionSheetIconCircleDanger: {
    backgroundColor: "rgba(255, 59, 48, 0.12)",
  },
  actionSheetTextBlock: { flex: 1, paddingRight: 10 },
  actionSheetRowTitle: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 3,
  },
  actionSheetRowSubtitle: {
    color: Colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 16,
  },
  compactTogglePill: {
    minWidth: 58,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: Radius.pill,
    alignItems: "center",
    justifyContent: "center",
  },
  compactToggleText: { fontSize: 13, fontWeight: "900" },
  restDurationRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: Colors.surface,
    borderRadius: Radius.lg,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  restDurationLabel: {
    color: Colors.textMuted,
    fontSize: 14,
    fontWeight: "800",
  },
  restDurationStepper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.background,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: "hidden",
  },
  restDurationStepButton: { paddingHorizontal: 14, paddingVertical: 8 },
  restDurationStepText: { color: Colors.text, fontSize: 18, fontWeight: "900" },
  restDurationValue: {
    color: Colors.text,
    fontSize: 14,
    fontWeight: "900",
    minWidth: 52,
    textAlign: "center",
  },
  modalContent: {
    backgroundColor: Colors.card,
    padding: 24,
    borderRadius: 24,
    width: "85%",
    alignItems: "center",
  },
  modalTitle: {
    color: Colors.text,
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
  },
  modalInput: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.borderStrong,
    color: Colors.text,
    fontSize: 18,
    paddingVertical: 12,
    marginBottom: 24,
    textAlign: "center",
    width: "100%",
  },
  modalButtonRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 20,
    width: "100%",
  },
  modalActionText: { color: Colors.text, fontSize: 16 },
  headerActionText: { color: Colors.text, fontSize: 17, fontWeight: "600" },
  toggleGroupWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    width: "100%",
    marginTop: 10,
  },
  modalGroupLabel: {
    color: Colors.textMuted,
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 10,
    textAlign: "center",
  },
  centeredEmptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  emptyStateText: {
    color: Colors.textMuted,
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 12,
  },
  emptyStateTextSmall: {
    color: Colors.textSubtle,
    fontSize: 14,
    textAlign: "center",
    width: "100%",
  },
  igCard: {
    backgroundColor: Colors.card,
    padding: 20,
    borderRadius: Radius.xl,
    width: "100%",
  },
  igCardHeader: {
    marginBottom: 16,
  },
  igCardTitle: {
    color: Colors.text,
    fontSize: 20,
    fontWeight: "800",
    textAlign: "center",
  },
  igCardDate: {
    color: Colors.textMuted,
    fontSize: 13,
    marginTop: 4,
    textAlign: "center",
  },
  igCardStatsRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 24,
  },
  igCardStatItem: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 12,
  },
  igCardStatText: {
    color: Colors.textMuted,
    fontSize: 13,
    fontWeight: "600",
    marginLeft: 6,
  },
  igCardExercisesWrapper: {},
  igCardExerciseContainer: {
    marginBottom: 16,
  },
  igCardExerciseHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  igCardExerciseName: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: "700",
  },
  igCard1RMLabel: {
    color: Colors.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  igCardSetRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  igCardSetNumber: {
    color: Colors.textMuted,
    fontSize: 14,
    width: 24,
    fontWeight: "600",
  },
  igCardSetText: {
    color: "#E5E5EA",
    fontSize: 15,
    flex: 1,
    fontWeight: "500",
  },
  igCard1RMValue: {
    color: Colors.textMuted,
    fontSize: 14,
    fontWeight: "600",
  },
  igCardMore: {
    color: Colors.accent,
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 8,
  },

  exerciseTitleHint: {
    color: Colors.textSubtle,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginTop: 4,
  },
  reorderInlineButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: "rgba(50, 215, 75, 0.35)",
    backgroundColor: "rgba(50, 215, 75, 0.1)",
    marginBottom: 14,
  },
  reorderInlineButtonText: {
    color: Colors.accent,
    fontSize: 13,
    fontWeight: "900",
    marginLeft: 6,
  },
  reorderModalContent: {
    width: "90%",
    maxHeight: "78%",
    backgroundColor: Colors.card,
    borderRadius: Radius.xxl,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 18,
    ...Platform.select({
      android: { elevation: 12 },
      ios: {
        shadowColor: "#000",
        shadowOpacity: 0.28,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 12 },
      },
    }),
  },
  reorderModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  reorderModalKicker: {
    color: Colors.accent,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 2,
    marginBottom: 6,
  },
  reorderModalTitle: {
    color: Colors.text,
    fontSize: 20,
    lineHeight: 24,
    fontWeight: "900",
    flexShrink: 1,
  },
  reorderModalSubtitle: {
    color: Colors.textMuted,
    fontSize: 13,
    fontWeight: "700",
    marginTop: 6,
  },
  reorderModalClose: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: Radius.pill,
    backgroundColor: Colors.elevated,
  },
  reorderExerciseRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: Radius.lg,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 10,
  },
  reorderExerciseRowActive: {
    borderColor: Colors.accent,
    backgroundColor: Colors.cardAlt,
  },
  reorderExerciseTitle: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  reorderExerciseSubtitle: {
    color: Colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
  },
  reorderModalFooter: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
  },
  reorderCancelButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
    borderRadius: Radius.lg,
    backgroundColor: Colors.elevated,
  },
  reorderCancelButtonText: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  reorderDoneButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
    borderRadius: Radius.lg,
    backgroundColor: Colors.accent,
  },
  reorderDoneButtonText: {
    color: Colors.black,
    fontSize: 16,
    fontWeight: "900",
  },

  // Reorder modal aliases used by WorkoutScreen and template editor
  reorderModalHandle: {
    width: 44,
    height: 5,
    borderRadius: Radius.pill,
    backgroundColor: Colors.elevated,
    alignSelf: "center",
    marginBottom: 16,
  },
  reorderModalList: {
    maxHeight: 430,
    width: "100%",
  },
  reorderModalRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: Radius.lg,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    marginBottom: 10,
  },
  reorderModalRowActive: {
    borderColor: Colors.accent,
    backgroundColor: Colors.cardAlt,
  },
  reorderModalIndexBadge: {
    width: 30,
    height: 30,
    borderRadius: Radius.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(50, 215, 75, 0.12)",
    marginHorizontal: 10,
  },
  reorderModalIndexText: {
    color: Colors.accent,
    fontSize: 12,
    fontWeight: "900",
  },
  reorderModalMeta: {
    color: Colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
  },
  reorderModalCancelButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
    borderRadius: Radius.lg,
    backgroundColor: Colors.elevated,
  },
  reorderModalCancelText: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  reorderModalDoneButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
    borderRadius: Radius.lg,
    backgroundColor: Colors.accent,
  },
  reorderModalDoneText: {
    color: Colors.black,
    fontSize: 16,
    fontWeight: "900",
  },

  actionMenuCard: {
    backgroundColor: Colors.card,
    borderRadius: Radius.xxl,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.xl,
    width: "90%",
    alignSelf: "center",
  },
  supersetGroupHeader: {
    marginHorizontal: 2,
    marginBottom: 10,
    marginTop: 4,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Colors.accent,
    backgroundColor: "rgba(50, 215, 75, 0.10)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  supersetGroupKicker: {
    color: Colors.accent,
    fontSize: 12,
    fontWeight: "900",
    letterSpacing: 1.8,
  },
  supersetGroupMeta: {
    color: Colors.textMuted,
    fontSize: 13,
    fontWeight: "800",
    marginTop: 4,
  },
  exerciseCardInSuperset: {
    borderColor: "rgba(50, 215, 75, 0.32)",
  },
  supersetPickerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  supersetPickerCheck: {
    width: 30,
    height: 30,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: Colors.borderStrong,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    backgroundColor: Colors.background,
  },
  supersetPickerCheckActive: {
    borderColor: Colors.accent,
    backgroundColor: Colors.accent,
  },
  supersetPickerTitle: {
    color: Colors.text,
    fontSize: 16,
    fontWeight: "900",
  },
  supersetPickerMeta: {
    color: Colors.textMuted,
    fontSize: 12,
    fontWeight: "700",
    marginTop: 3,
  },
});
